version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - product_api_network

  nginx:
    image: nginx:alpine
    container_name: product_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - product_api_network

  db:
    image: mysql:8.0
    container_name: product_api_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: product_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: product_api
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - product_api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: product_api_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - product_api_network

volumes:
  db_data:

networks:
  product_api_network:
    driver: bridge

